#!/usr/bin/env python3
import os
import sys

path = sys.stdin.readline()

path = path.replace('\n', '')
path = path.replace(os.environ['HOME'], '~')

if not path:
    exit

if len(path) > 16:
    path = path.split('/')
    path = '/'.join([path[-2], path[-1]])

print(path)
